# Generated by Django 4.2.4 on 2023-08-22 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('noteId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=65)),
                ('color', models.CharField(default='GREY', max_length=50)),
                ('isTrashed', models.BooleanField(default=False)),
                ('isPinned', models.BooleanField(default=False)),
                ('isArchived', models.BooleanField(default=False)),
                ('textContent', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=60)),
                ('userEditedTimestamp', models.DateTimeField(auto_now=True)),
                ('createdTimestamp', models.DateTimeField(auto_now_add=True)),
                ('labels', models.CharField(default='personal', max_length=50)),
            ],
        ),
    ]
